### ISSUE TITLE
Not enoug information about how to use migrations

### ISSUE THREAD

**Issue by symfonysos** [symlex/symlex#10]
I can see in the framework docs that there are some "migration" commands - but there is no documentation about how to actually use these migrations. Is there something that creates models? Something like the symfony maker bundle? I guess that maker bundle itself will not be compatible.  
Is this the exact same thing like symfony migrations?

**Comment by lastzero** [comment]
No bundles, no code generators. It's the Doctrine DBAL migrations, not the ORM migrations. The files are in the app/db directory.

**Comment by lastzero** [comment]
Real SQL 👍

**Comment by lastzero** [comment]
I'll close this now. Create a new issue or preferably [use our chat](https://gitter.im/symlex/community) if you have more questions.
