### ISSUE TITLE
Installation: Mismatch between code and documentation

### ISSUE THREAD

**Issue by ghosttk** [symlex/symlex#14]
There is no dev.xml ,  only build.xml, and running it will report syntax error. 
After running 'docker-compose up' and 'docker-compose exec php sh'.

```
/var/www/html # bin/phing build
Buildfile: /var/www/html/build.xml

App > build:


App > build-database:

Are you sure you wish to drop the database "web"? (y/n)y
Database "web" dropped
Database "web" created
Loading configuration from file: migrations.yml

Parse error: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 29
[phingcall] /var/www/html/build.xml:33:96: Task exited with code 255

BUILD FAILED
/var/www/html/build.xml:25:43: Execution of the target buildfile failed. Aborting.

```

And running ' make terminal ' didn't work too.
`make: *** No rule to make target 'terminal'.  Stop.`

**Comment by lastzero** [comment]
Sorry, need to update the docs... where did you find this? The README says to use make, we don't use phing anymore as it requires php and composer. So we can't run composer with it in the first place.

**Comment by lastzero** [comment]
Updated our docs: https://docs.symlex.org/en/latest/framework/

I'll close this for now. Let us know if you find other outdated information. Using RoadRunner and Make was the only major change recently. I'd consider the framework complete otherwise.

**Comment by ghosttk** [comment]
I also tried the latest docs, but running 'make terminal' and 'make all database' still doesn't work.
'make ' command says 'no rules to build target'.
I guess it need some makefiles?

**Comment by lastzero** [comment]
Maybe it's because composer will download an older version... There's a Makefile in the repo.

![Screenshot_20191218_075100](https://user-images.githubusercontent.com/301686/71062610-3bfee800-216b-11ea-8b8c-668f9726f544.jpg)

**Comment by ghosttk** [comment]
That's right, all the files installed via composer are old, including file structure and README.md.
I copy the Makefile from the repo to my directory and run 'make terminal', it reports: 
`ERROR: No such service: app`

**Comment by lastzero** [comment]
@ghosttk Just tagged 4.4.0, should soon be discovered by composer as stable release. You'll have to run `composer create-project symlex/symlex myapp` again and follow the instructions.

All tests green over here. Also further improved and updated our docs, there were in fact some changes compared to older releases as we switched to RoadRunner and TestCafe (was nginx and codeception before).

Make sure you're in the right directory and use Symlex 4.4.0 when you run commands (see [CHANGELOG](https://github.com/symlex/symlex/blob/master/CHANGELOG.md)).

Let me know if this works :)

**Comment by lastzero** [comment]
> That's right, all the files installed via composer are old, including file structure and README.md.
> I copy the Makefile from the repo to my directory and run 'make terminal', it reports:
> `ERROR: No such service: app`

Using the new `Makefile` with the previous release wouldn't work as the old version had a `web` and  `php` service for nginx and phpfpm. The new version only has an `app` service. We don't need nginx and phpfpm anymore. If you prefer nginx, you'll have to use an old release or copy the old config to the new release... our demo still uses nginx and also some examples.

The instructions in the README files in the repos should always be right for the version you are using. The latest README on GitHub might not always work, if you use a different release.

**Comment by lastzero** [comment]
FYI: Version 4.4.1 is upgraded to RoadRunner 1.5.2, Symfony 4.4.1 and PHP 7.4. Just released. Hope you like it.

**Comment by ghosttk** [comment]
Today I create a new project via composer, this time all files are updated and every thing goes well.
Thank you!
