### ISSUE TITLE
Not enough information about Authentication and Authorization

### ISSUE THREAD

**Issue by symfonysos** [symlex/symlex#8]
The demo app screenshots show some basic user management, however there is not enough information about how to implement authenticaion and authorization with this framework - while browsing the docs I found one single page about "Interceptors" that seem to be related to this, but I am not able to find that page again, it was hidden in some very specific library description and not where I am expecting it. Auth & Auth are most important parts of a framework and should have a very prominent place in the documentation - it would be great to better understand how to implement:

- handling of roles / groups / permissions e.g. in a RBAC-like schema
- object-level security ("only edit my posts") in the controller, the view and the database layer 
- login / logout / "remember me" / several authentication schemas like e.g. oauth with social auth providers
- controllers, models and security in a way that makes sense with the framework paradigm

Also an extended example app (that only needs php, nothing else!) would be a great way to better understand your approach to these important things.

Thank you very much for your attention!

**Comment by lastzero** [comment]
It's a lean Web framework, not a complete CMS with User Management. Right now, you'd actually have to read the few lines of code that are there, mainly Session service and SessionController. It's using localStorage, so a pure REST & JS solution. Every project & company has different auth requirements. I could write a book about it and there still would be questions and many developers would say they want it differently implemented for whatever reason. You can do the auth in any way you like, the example is just an example.

If you need hints, there is community chat (it's better than writing tickets for each question): https://gitter.im/symlex/community

**Comment by lastzero** [comment]
PS: No framework paradigm, except: Use real code and write a test for it. It's not like with some other frameworks where you first have to learn a list of custom annotations to make it work or install a bundle because it's too difficult otherwise.

**Comment by lastzero** [comment]
I'll close this now. Create a new issue or preferably [use our chat](https://gitter.im/symlex/community) if you have more questions.
