### ISSUE TITLE
Not enough information about how to handle complex model relations

### ISSUE THREAD

**Issue by symfonysos** [symlex/symlex#9]
One more thing: currently I am not sure I can interpolate from the existing docs how I would implement a complex form with multiple models involved with this framework - it would be very interesting to see a real life example with multiple model relations, as the ultra-simplistic examples in the docs give no opportunity to show how to work with your framework in a more realistic scenario. Of course with auth and auth :)

Thanks again and I hope this will become a very popular alternative to other frameworks - looks very promising!

**Comment by lastzero** [comment]
I could show you (maybe via chat). For example, you could use a form, get values by tag (instead of getting all values) and assign them to a model. Or you can access single values and assign them to model values manually. It totally depends on your code and your style. But the simple solution is to tag your form fields (should be documented, but more example would certainly be nice - maybe somebody can contribute them?).

**Comment by lastzero** [comment]
PS: Don't expect a lot of magic and annotations that do things for you somehow.

**Comment by symfonysos** [comment]
hmm, I found three entries mentioning "tags" in the docs, however these do not explain anything about how to define relationships in the models or how to create master-detail views of multiple connected models. 

I certainly at this point can not contribute to the docs, as I am just trying to understand how your framework works, but I hope I may be allowed to give a hint about the docs: it is a bit unclear about the boundaries between your code and the involved frameworks, where "symfony practices" can be applied and where doctrine docs are valid. 

It would be great if the doc writer assumed, that the reader does _not_ completely know all of symfony and all of doctrine, so it would be great to precisely show where knowledge from these other frameworks needs to be applied.

E.g. I can find no info in the docs for important things like "onetomany" or "manytomany" ("no matching documents", also reading the db layer docs I did not found anything) so it is a mystery how these kind of relations should be implemented with your framework.

**Comment by lastzero** [comment]
Haha, yes, you have to code that. I think there are a few helper methods in the Entity DAO for the SQL. But at the end you have to write code like that:

```
class User {
  function getComments() {
     return $this->createModel('Comment')->findAll(['userId' => $this->getId()]);
  }
}
```

For me, this is very simple to write and understand, but I know many developers are used to config files, annotations and generators nowadays.

**Comment by lastzero** [comment]
If you like this, please contribute 👍 

Some pull requests for the documentation would be amazing.

Many things are actually very simple to solve (of course, if you know how, but I can always answer questions). Sorry that I can't publish the proprietary code of commercial projects that are using this framework. Also I don't want to make the example too complex.

**Comment by lastzero** [comment]
I'll close this now. Create a new issue or preferably [use our chat](https://gitter.im/symlex/community) if you have more questions.
